#NumPy


In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(a[2:None])

[3 4 5]


In [7]:
a = np.arange(4)
b = a.reshape(2,2)
print(b)

[[0 1]
 [2 3]]


In [8]:
a = np.arange(10)
b = np.where(a % 2 == 1, 1, a)
print(b)


[0 1 2 1 4 1 6 1 8 1]


In [9]:
a = np.array([1,2,3,4])
a[0] = 0.9
print(a[0], a.dtype)

0 int32


In [10]:
a = np.array([3,6,9,12,15])
b = np.array([3,4,6,8,12])
c = np.where(a == b, a, "False")
print(c[0])

3


##Creating np Arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0, 2, 4, 6, 8, 10])
print(arr)

[ 0  2  4  6  8 10]


In [ ]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(6,)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

In [ ]:
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

In [ ]:
np.ones((2, 3, 4), )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
1729 * np.ones((2, 3, 4), )

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [ ]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3) # numbers under normal dist. with mean = 0 and var. = 1

array([[-0.23715263, -0.91356407,  0.02607066],
       [ 0.044634  , -1.20485254, -1.1750192 ]])

In [ ]:
np.random.rand(2, 3) # numbers under uniform dist. b/w 0 and 1

array([[0.97665569, 0.43926203, 0.49034169],
       [0.02654901, 0.48057913, 0.51838621]])

In [ ]:
np.random.randint(0, 100, (2, 3)) # random integers b/w min. and max. provided

array([[10, 53, 42],
       [26, 51, 22]])

In [ ]:
np.arange(7, 70, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [ ]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
str_arr = np.array(['1.4', '2.1', '1.1'])
str_arr

array(['1.4', '2.1', '1.1'], dtype='<U3')

In [ ]:
arr = np.array(str_arr, dtype = "float")
arr

array([1.4, 2.1, 1.1])

##Indexing


In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0, 0, 0]

1

In [ ]:
arr3d[1, 1, 2]

12

In [ ]:
i = 0
j = 1
k = 2

arr3d[i, j, k]

6

In [ ]:
arr3d[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d[0, 1:, 1:]

array([[5, 6]])

In [ ]:
#To get a sliced array
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
#To check whether the elements are even
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
#To get all even values as an array
arr3d[arr3d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr3d[(arr3d % 2 == 1) & (arr3d > 4)]

array([ 5,  7,  9, 11])

In [ ]:
arr_slice = arr3d[0, :, :]
arr_slice

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_slice[0, 0] = 1729 #The value in the org array also changes
arr_slice

array([[1729,    2,    3],
       [   4,    5,    6]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr_slice = np.copy(arr3d[0, :, :]) #Creating a copy
arr_slice[0, 0] = 1 #The value in the org array doesn't change
arr_slice

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr = np.random.randint(0, 10, (5))
arr

array([6, 6, 0, 0, 1])

In [ ]:
#Indexing with a list
my_indices = [1, 3, 4]
arr[my_indices]

array([6, 0, 1])

##Operations

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [ ]:
arr1

array([[0.74679795, 0.02240421, 0.23883386, 0.78210845],
       [0.15261908, 0.88577501, 0.79397983, 0.67442232],
       [0.90672547, 0.19465221, 0.65570443, 0.22756726]])

In [ ]:
arr2

array([[0.34735721, 0.76097172, 0.24991868, 0.73795284],
       [0.75948009, 0.92396916, 0.56928842, 0.59032678],
       [0.33466549, 0.37487017, 0.94552857, 0.5030354 ]])

In [ ]:
arr1 + arr2

array([[1.09415516, 0.78337593, 0.48875254, 1.52006129],
       [0.91209917, 1.80974418, 1.36326824, 1.2647491 ],
       [1.24139096, 0.56952238, 1.601233  , 0.73060266]])

In [ ]:
arr1 * arr2

array([[0.25940565, 0.01704897, 0.05968904, 0.57715915],
       [0.11591115, 0.8184288 , 0.45200352, 0.39812956],
       [0.30344972, 0.07296931, 0.61998727, 0.11447439]])

In [ ]:
np.exp(arr1) #exponentiate each value in an array

array([[2.11023212, 1.02265707, 1.26976756, 2.18607665],
       [1.16488117, 2.42486297, 2.21218304, 1.96289872],
       [2.47620084, 1.21488839, 1.92649913, 1.25554188]])

In [ ]:
np.log(np.exp(arr1))

array([[0.74679795, 0.02240421, 0.23883386, 0.78210845],
       [0.15261908, 0.88577501, 0.79397983, 0.67442232],
       [0.90672547, 0.19465221, 0.65570443, 0.22756726]])

In [ ]:
np.sin(arr1)

array([[0.67929236, 0.02240234, 0.23656975, 0.70477678],
       [0.15202729, 0.77440556, 0.71314882, 0.62444621],
       [0.78748978, 0.19342533, 0.60971774, 0.22560817]])

In [ ]:
np.sqrt(arr1)

array([[0.86417472, 0.14968036, 0.48870631, 0.88436896],
       [0.39066492, 0.94115621, 0.89105546, 0.8212322 ],
       [0.95222133, 0.44119408, 0.80975579, 0.4770401 ]])

In [ ]:
arr_inv = 1 / arr1
arr_inv

array([[ 1.33905028, 44.63446683,  4.18701101,  1.27859505],
       [ 6.55226061,  1.12895485,  1.25947784,  1.48275045],
       [ 1.10286965,  5.13736774,  1.52507739,  4.39430531]])

In [ ]:
arr0 = np.zeros((3, 5))
arr_inv = 1 / arr0
arr_inv

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [ ]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [ ]:
np.isinf(arr_inv[0, 0])

True

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

##Exercise: Finding no. of points outside nd sphere

In [ ]:
nd = 2
npoints = 100000

In [ ]:
points = np.random.rand(npoints, nd)
points

array([[0.57189653, 0.79924834],
       [0.0157265 , 0.13546739],
       [0.12479049, 0.26019079],
       ...,
       [0.38303212, 0.5184418 ],
       [0.93332769, 0.91193698],
       [0.57335147, 0.74148302]])

In [ ]:
#distance from origin
dfo = np.zeros((npoints, 1))
dfo
outside_points = 0

In [ ]:
%%time
for i in range(npoints):
    for j in range(nd):
        dfo[i][0] += points[i, j] ** 2
    dfo[i][0] = np.sqrt(dfo[i])
    if dfo[i][0] > 1:
        outside_points += 1

CPU times: user 524 ms, sys: 794 µs, total: 525 ms
Wall time: 529 ms


In [ ]:
# 1 - (3.14/4) = 0.214999997
print('Fraction of points outside is: ', outside_points/npoints )

Fraction of points outside is:  0.21376


In [ ]:
dfo[ dfo > 1]

array([1.09614367, 1.04216395, 1.02134809, ..., 1.07627621, 1.02195175,
       1.30488683])

In [ ]:
%%time
sq_points = points * points
dfo = np.sqrt(np.sum(sq_points, axis = 1)) # rows: axis - 0, columns: axis - 1
outside_points = np.sum(dfo > 1)

CPU times: user 5.08 ms, sys: 1.73 ms, total: 6.81 ms
Wall time: 8.5 ms


In [ ]:
print('Fraction of points outside is: ', outside_points/npoints )

Fraction of points outside is:  0.21376


In [ ]:
%%time
outside_points = np.sum( np.sqrt(np.sum(points * points, axis = 1)) > 1)

CPU times: user 4.64 ms, sys: 950 µs, total: 5.59 ms
Wall time: 8.32 ms


In [ ]:
def area_outside_square(npoints, nd):
    points = np.random.rand(npoints, nd)
    return np.sum( np.sqrt(np.sum(points * points, axis = 1)) > 1) / npoints

In [ ]:
area_outside_square(100000, 2)

0.21451

In [ ]:
for i in range(2, 11):
    print(i, area_outside_square(100000, i))

2 0.21434
3 0.47553
4 0.69312
5 0.83612
6 0.91927
7 0.96398
8 0.98382
9 0.99356
10 0.9976


#Broadcasting

In [ ]:
arr1 = np.arange(6)
arr1.shape

(6,)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1 = arr1.reshape((2, 3))

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((2, 3))

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr1 + arr2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
arr2[0]

array([0, 1, 2])

In [ ]:
arr1 + arr2[0] # (2, 3) + (1, 3)

array([[0, 2, 4],
       [3, 5, 7]])

In [ ]:
arr1[0, :] + arr2 # (1, 3) + (2, 3)

array([[0, 2, 4],
       [3, 5, 7]])

In [ ]:
arr1 + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3 = np.arange(24).reshape((2, 3, 4))

In [ ]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr1s = np.ones((1, 4), dtype = np.int64)

In [ ]:
arr1s

array([[1, 1, 1, 1]])

In [ ]:
arr3 + arr1s # (2, 3, 4) + (1, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
arr3.T # Transpose

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

#File Handling

In [15]:
planets_small = np.loadtxt("Planets_small.txt")

ValueError: could not convert string to float: 'MERCURY'

In [ ]:
planets_small = np.loadtxt("Planets_small.txt",
                           skiprows = 1)

ValueError: ignored

In [ ]:
planets_small = np.loadtxt("Planets_small.txt",
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [ ]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets_small.shape

(3, 9)

In [ ]:
planets = np.loadtxt("Planets.txt",
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: ignored

In [16]:
planets = np.genfromtxt("Planets.txt", 
                        skip_header = 1,
                        usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [17]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [18]:
planets.shape

(20, 9)

In [19]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [20]:
planets_new = np.nan_to_num(planets, nan = -1)

In [21]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [22]:
np.savetxt('planets_new.txt',
        planets_new,
        delimiter = ',')

In [23]:
np.save("planets_new", planets_new)

In [24]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [25]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [26]:
np.savez("many_arrs", arr1, arr2, arr3)

In [27]:
arrs = np.load('many_arrs.npz')

In [28]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [29]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [30]:
arrs['arr_0']

array([[0.56407367, 0.61517037, 0.73427601, ..., 0.39603459, 0.80503251,
        0.54625413],
       [0.49605052, 0.18638785, 0.53858227, ..., 0.2538667 , 0.94734756,
        0.27165904],
       [0.29696167, 0.90252495, 0.13795643, ..., 0.35808562, 0.16055919,
        0.58610943],
       ...,
       [0.78979061, 0.06096482, 0.27554844, ..., 0.00629044, 0.07681792,
        0.52164579],
       [0.20732613, 0.90389906, 0.90150282, ..., 0.44256678, 0.11141588,
        0.14911752],
       [0.85653958, 0.3748667 , 0.07866992, ..., 0.55526648, 0.88245823,
        0.55182267]])

In [31]:
arrs["arr_0"].shape

(1000, 10)

In [32]:
np.savez_compressed('many_arrs_compressed',
                    arr1, arr2, arr3)

In [33]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [34]:
arr1 = np.zeros((10000, 10000))

In [35]:
np.savez("zeros", arr1)

In [36]:
np.savez_compressed("zeros_compressed", arr1)

In [37]:
!ls -lh

'ls' is not recognized as an internal or external command,
operable program or batch file.


#Stats with NumPy

In [38]:
arr = np.random.rand(1000000,)
arr

array([0.7974009 , 0.34438165, 0.30411639, ..., 0.75417217, 0.76108689,
       0.19003985])

In [39]:
np.amin(arr)

1.2346026019294243e-06

In [40]:
np.amax(arr)

0.9999972145493575

In [41]:
np.mean(arr)

0.4998770402678327

In [42]:
np.var(arr)

0.08340175215404014

In [43]:
np.std(arr)

0.28879361515456003

In [44]:
np.median(arr)

0.4996053732128675

In [45]:
np.percentile(arr, 50)

0.4996053732128675

In [46]:
np.percentile(arr, 10)

0.10001230091521619

In [47]:
np.percentile(arr, 90)

0.9001687730413832

In [48]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

Wall time: 72 ms


In [49]:
iqr

0.5007506307388212

In [50]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

Wall time: 32 ms


In [51]:
iqr

0.5007506307388212

In [52]:
# z-score
(arr - np.mean(arr))/np.std(arr)

array([ 1.03023006, -0.53843084, -0.67785656, ...,  0.88054276,
        0.90448623, -1.07286719])

In [53]:
np.histogram(arr)

(array([ 99978, 100037, 100368,  99899, 100135,  99892,  99693,  99694,
        100133, 100171], dtype=int64),
 array([1.23460260e-06, 1.00000833e-01, 2.00000431e-01, 3.00000029e-01,
        3.99999627e-01, 4.99999225e-01, 5.99998823e-01, 6.99998421e-01,
        7.99998019e-01, 8.99997617e-01, 9.99997215e-01]))

In [54]:
np.histogram(arr, bins = 5)

(array([200015, 200267, 200027, 199387, 200304], dtype=int64),
 array([1.23460260e-06, 2.00000431e-01, 3.99999627e-01, 5.99998823e-01,
        7.99998019e-01, 9.99997215e-01]))

In [55]:
np.histogram(arr, bins = [0, 0.25, 0.5, 0.75, 1])

(array([250414, 250003, 249257, 250326], dtype=int64),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [56]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [57]:
np.digitize(arr, bins) #mapping of element to bin

array([4, 2, 2, ..., 4, 4, 1], dtype=int64)

In [58]:
arr1 = np.random.randint(0, 10, (10))

In [59]:
arr1

array([6, 9, 2, 2, 8, 6, 3, 3, 7, 7])

In [60]:
bins = [0, 6, 10]

In [61]:
np.digitize(arr1, bins) #left inclusive and right exclusive

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 2], dtype=int64)

In [62]:
np.digitize(arr1, bins, right = True) #right inclusive

array([1, 2, 1, 1, 2, 1, 1, 1, 2, 2], dtype=int64)

In [63]:
arr1 = np.random.randint(50, 80, 100) # weight

In [64]:
arr1

array([54, 54, 59, 70, 56, 76, 79, 67, 63, 74, 69, 58, 73, 69, 60, 54, 59,
       75, 68, 51, 77, 65, 75, 69, 65, 75, 63, 53, 54, 62, 63, 63, 79, 59,
       50, 74, 65, 65, 71, 67, 57, 70, 51, 52, 58, 55, 73, 64, 53, 64, 61,
       64, 70, 72, 62, 72, 50, 68, 63, 56, 72, 73, 63, 65, 57, 72, 78, 78,
       53, 57, 71, 61, 50, 52, 68, 75, 68, 74, 66, 57, 73, 62, 73, 73, 78,
       52, 62, 75, 70, 76, 75, 52, 59, 57, 70, 50, 68, 66, 71, 72])

In [65]:
arr2 = np.random.randint(150, 185, 100) # height

In [66]:
arr3 = np.random.randint(17, 22, 100) # age

In [67]:
np.concatenate((arr1, arr2, arr3))

array([ 54,  54,  59,  70,  56,  76,  79,  67,  63,  74,  69,  58,  73,
        69,  60,  54,  59,  75,  68,  51,  77,  65,  75,  69,  65,  75,
        63,  53,  54,  62,  63,  63,  79,  59,  50,  74,  65,  65,  71,
        67,  57,  70,  51,  52,  58,  55,  73,  64,  53,  64,  61,  64,
        70,  72,  62,  72,  50,  68,  63,  56,  72,  73,  63,  65,  57,
        72,  78,  78,  53,  57,  71,  61,  50,  52,  68,  75,  68,  74,
        66,  57,  73,  62,  73,  73,  78,  52,  62,  75,  70,  76,  75,
        52,  59,  57,  70,  50,  68,  66,  71,  72, 177, 150, 154, 159,
       165, 156, 174, 163, 163, 169, 171, 164, 151, 154, 153, 161, 162,
       176, 169, 162, 183, 180, 165, 161, 166, 171, 156, 167, 157, 176,
       162, 152, 153, 159, 182, 170, 171, 156, 158, 184, 181, 155, 184,
       158, 155, 155, 177, 161, 182, 174, 174, 153, 172, 151, 166, 159,
       158, 152, 173, 169, 160, 163, 156, 164, 163, 160, 177, 154, 164,
       172, 161, 161, 182, 157, 161, 175, 178, 175, 156, 181, 16

In [68]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [69]:
np.vstack((arr1, arr2, arr3))

array([[ 54,  54,  59,  70,  56,  76,  79,  67,  63,  74,  69,  58,  73,
         69,  60,  54,  59,  75,  68,  51,  77,  65,  75,  69,  65,  75,
         63,  53,  54,  62,  63,  63,  79,  59,  50,  74,  65,  65,  71,
         67,  57,  70,  51,  52,  58,  55,  73,  64,  53,  64,  61,  64,
         70,  72,  62,  72,  50,  68,  63,  56,  72,  73,  63,  65,  57,
         72,  78,  78,  53,  57,  71,  61,  50,  52,  68,  75,  68,  74,
         66,  57,  73,  62,  73,  73,  78,  52,  62,  75,  70,  76,  75,
         52,  59,  57,  70,  50,  68,  66,  71,  72],
       [177, 150, 154, 159, 165, 156, 174, 163, 163, 169, 171, 164, 151,
        154, 153, 161, 162, 176, 169, 162, 183, 180, 165, 161, 166, 171,
        156, 167, 157, 176, 162, 152, 153, 159, 182, 170, 171, 156, 158,
        184, 181, 155, 184, 158, 155, 155, 177, 161, 182, 174, 174, 153,
        172, 151, 166, 159, 158, 152, 173, 169, 160, 163, 156, 164, 163,
        160, 177, 154, 164, 172, 161, 161, 182, 157, 161, 175, 178, 17

In [70]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [71]:
arr2d = np.vstack((arr1, arr2, arr3))

In [72]:
np.amin(arr2d)

17

In [73]:
np.amin(arr2d, axis = 1)

array([ 50, 150,  17])

In [74]:
np.mean(arr2d, axis = 1)

array([ 64.81, 165.49,  18.93])

In [75]:
np.mean(arr2d[1, :])

165.49

#Rules of Stats


In [76]:
#Mean subtracted array has zero mean
arr = np.random.rand(1000)

In [77]:
mean = np.mean(arr)

In [78]:
arr1 = arr - mean

In [79]:
np.mean(arr1)

7.105427357601002e-18

In [80]:
#Computing mean with smaller set of values
arr = np.random.rand(1000)

In [81]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.7101528573516179
2 0.41556833748860106
3 0.37490657944685996
4 0.43415445862506585
5 0.4434989225236158
6 0.4959590411965375
7 0.48744984753929776
8 0.47118345483267315
9 0.5204659053218573
10 0.4855463489258101
11 0.4603727707982399
12 0.4574286993521979
13 0.4586451006833224
14 0.4754694295310347
15 0.4746433897222009
16 0.4870440433115004
17 0.475213147338311
18 0.4504551641518323
19 0.4282965276254571
20 0.40826110110089003
21 0.401342364877789
22 0.40369480958815607
23 0.4265854148811371
24 0.4337709204861742
25 0.4561319570500231
26 0.46798817773168483
27 0.48711105914146036
28 0.5024975264075185
29 0.49526286345331305
30 0.49613441444801964
31 0.49008052095800164
32 0.4984636267039133
33 0.503218349463862
34 0.5101821712841924
35 0.5078542299007062
36 0.5175706079648688
37 0.5256076353531609
38 0.5300287138087163
39 0.5271975722073369
40 0.5242937606617104
41 0.5174765247244782
42 0.5271031328519582
43 0.5168330876838371
44 0.5224965753239109
45 0.5179850463612387
46 0.51309

In [82]:
means = np.cumsum(arr)/np.arange(1, 1001) #alternative for the above

In [83]:
means[0:20]

array([0.71015286, 0.41556834, 0.37490658, 0.43415446, 0.44349892,
       0.49595904, 0.48744985, 0.47118345, 0.52046591, 0.48554635,
       0.46037277, 0.4574287 , 0.4586451 , 0.47546943, 0.47464339,
       0.48704404, 0.47521315, 0.45045516, 0.42829653, 0.4082611 ])

In [84]:
#Effect of outliers on mean and median

In [85]:
arr = np.random.randint(1, 100, 100)

In [86]:
np.mean(arr)

48.38

In [87]:
np.median(arr)

53.5

In [88]:
arr = np.append(arr, [1000, 2000])

In [89]:
np.mean(arr)

76.84313725490196

In [90]:
np.median(arr)

55.0

In [91]:
# Effect of scaling arrays on mean and median

In [92]:
arr = np.random.rand(100)

In [93]:
np.mean(arr)

0.5422882886359139

In [94]:
np.median(arr)

0.5591762946575791

In [95]:
arr1 = 2.5 * arr + 0.65

In [96]:
print( np.mean(arr1), 2.5 * np.mean(arr) + 0.65 )

2.0057207215897845 2.005720721589785


In [97]:
print( np.median(arr1), 2.5 * np.median(arr) + 0.65 )

2.0479407366439477 2.0479407366439477


In [98]:
print( np.var(arr1), 2.5 * np.var(arr) + 0.65 )

0.5122841625716362 0.8549136650286545


In [99]:
print( np.var(arr1), 2.5**2 * np.var(arr) )

0.5122841625716362 0.5122841625716362


In [100]:
print( np.std(arr1), 2.5* np.std(arr) )

0.7157402898898707 0.7157402898898707


# Case Study

In [101]:
!head cric_data.tsv

'head' is not recognized as an internal or external command,
operable program or batch file.


1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has scored a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean of Sachin's scores based on which quartile India's score falls in
7.   For every match, find out who has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on an average after having scored x runs
9.  How many matches did sachin take to score first 1000 runs, next 1000 runs...


In [103]:
arr = np.genfromtxt("cric_data.tsv",
                  skip_header = 1,
                  usecols = (0, 1, 2, 3))

arr

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  85.,  12., 224.],
       [ 10.,  18.,  63., 161.],
       [ 11.,   4., 107., 276.],
       [ 12.,   7.,  76., 283.],
       [ 13.,  37.,   4., 297.],
       [ 14.,  14.,   5., 139.],
       [ 15.,   0.,  33., 224.],
       [ 16.,   4.,   7., 178.],
       [ 17.,   0.,   0.,   0.],
       [ 18.,  21.,  36., 193.],
       [ 19.,   1.,  66., 231.],
       [ 20.,  62.,   0., 134.],
       [ 21.,   0., 123., 246.],
       [ 22., 138.,  39., 299.],
       [ 23.,  38.,   9., 242.],
       [ 24.,   2.,  11., 214.],
       [ 25.,  46.,  14., 152.],
       [ 26.,  65.,   0., 104.],
       [ 27.,   0.,   0.,   4.],
       [ 28.,  39.,  26., 155.],
       [ 29.,  48.,   4., 168.],
       [ 3

In [104]:
arr.shape

(225, 4)

In [105]:
# Find mean, median, IQR for Sachin, Rahul, and India

np.mean(arr[:, 1:4], axis = 0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [106]:
np.median(arr[:, 1:4], axis = 0)

array([ 27.,  22., 216.])

In [107]:
p25_75 = np.percentile(arr[:, 1:4], [25, 75], axis = 0)

In [108]:
iqrs = p25_75[1] - p25_75[0]
iqrs

array([57., 46., 98.])

In [109]:
# Find the histogram of Sachin's scores with 10 bins

In [110]:
np.histogram(arr[:, 1], bins = 10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [111]:
# Find mean of Sachin's scores grouped by 25 matches

In [112]:
sachin_25s = arr[:, 1].reshape(9, 25)

In [114]:
np.mean(sachin_25s, axis = 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [115]:
# Find mean of Sachin's scores where he has scored a century

In [116]:
np.mean(arr[arr[:, 1]>= 100 ][:, 1])

125.0

In [117]:
# Find mean of Sachin's scores when Rahul has scored less than 10

In [118]:
np.mean(arr[arr[:, 2] <= 10 ][:, 1])

40.2112676056338

In [119]:
# Find mean of Sachin's scores based on which quartile India's score falls in

In [120]:
qrs = np.percentile(arr[:, 3], [25, 50, 75, 100])

In [122]:
qrs = qrs.reshape(4, 1)

In [123]:
indices = arr[:, 3] < qrs

In [124]:
indices.shape

(4, 225)

In [125]:
arr[ indices[0, :] ][:, 1]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [126]:
for i in range(4):
    print(np.mean( arr[indices[i, :]][:, 1] ) )

19.672727272727272
28.18018018018018
31.688622754491018
39.799107142857146


In [127]:
# For every match, find out who has scored more - Sachin or Rahul

In [128]:
is_rahul_higher = np.argmax(arr[:, 1:3], axis = 1) #gives position of max. value

In [129]:
np.where(is_rahul_higher == 0, "Sachin", "Rahul")

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

In [130]:
# How many more runs does Sachin score on an average after having scored x runs

In [131]:
def maxAfterX(x):
    print( np.mean(arr[arr[:, 1] >= x][:, 1] - x) )

In [132]:
maxAfterX(5)

45.61363636363637


In [133]:
# How many matches did sachin take to score first 1000 runs, next 1000 runs...

In [134]:
sachin_cumscores = np.cumsum(arr[:, 1])

In [135]:
np.histogram(sachin_cumscores, bins = np.arange(0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int64),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))